# Generated by Django 5.1.1 on 2024-09-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gunpla',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
