# Generated by Django 5.1.1 on 2024-09-07 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_gunpla_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gunpla',
            old_name='user_reviews',
            new_name='descriptions',
        ),
    ]
