# Generated by Django 5.1.1 on 2024-09-07 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_user_reviews_gunpla_descriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gunpla',
            old_name='descriptions',
            new_name='notes',
        ),
    ]
