# Generated by Django 5.1.1 on 2024-09-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_descriptions_gunpla_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='gunpla',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AlterField(
            model_name='gunpla',
            name='price',
            field=models.IntegerField(),
        ),
    ]
