# Generated by Django 5.1.1 on 2024-09-13 13:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_gunpla_description_alter_gunpla_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gunpla',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
