# Generated by Django 5.1.1 on 2024-09-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_gunpla_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gunpla',
            name='notes',
            field=models.TextField(default='No notes available'),
        ),
    ]
