# Generated by Django 5.1.1 on 2024-11-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_gunpla_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gunpla',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='gunpla',
            name='extensions',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='gunpla',
            name='notes',
            field=models.TextField(default=None),
        ),
    ]
